version: 0.2

phases:
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn clean compile package
artifacts:
  files:
    - resume-0.0.1-SNAPSHOT.war
  discard-paths: yes